// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	DURATIONTOOLONG     ErrorCode = "DURATION_TOO_LONG"
	INVALIDPASSCODE     ErrorCode = "INVALID_PASSCODE"
	INVALIDTIMEINTERVAL ErrorCode = "INVALID_TIME_INTERVAL"
	INVALIDTIMERANGE    ErrorCode = "INVALID_TIME_RANGE"
	PASTTIME            ErrorCode = "PAST_TIME"
	RANGETOOLARGE       ErrorCode = "RANGE_TOO_LARGE"
	TIMECONFLICT        ErrorCode = "TIME_CONFLICT"
)

// CreateReservationRequest defines model for CreateReservationRequest.
type CreateReservationRequest struct {
	// DjName DJ display name (emojis allowed)
	DjName string `json:"djName"`

	// EndTime Must be on 15-minute intervals, max 1 hour from start
	EndTime time.Time `json:"endTime"`

	// Passcode 4-digit passcode for deletion
	Passcode string `json:"passcode"`

	// StartTime Must be on 15-minute intervals
	StartTime time.Time `json:"startTime"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// Reservation defines model for Reservation.
type Reservation struct {
	CreatedAt time.Time `json:"createdAt"`

	// DjName DJ display name (emojis allowed)
	DjName    string             `json:"djName"`
	EndTime   time.Time          `json:"endTime"`
	Id        openapi_types.UUID `json:"id"`
	StartTime time.Time          `json:"startTime"`
}

// StreamStatus defines model for StreamStatus.
type StreamStatus struct {
	// CurrentDj Name of current DJ (null if no one is scheduled)
	CurrentDj *string `json:"currentDj,omitempty"`

	// CurrentEndTime End time of current session
	CurrentEndTime *time.Time `json:"currentEndTime,omitempty"`

	// CurrentStartTime Start time of current session
	CurrentStartTime *time.Time `json:"currentStartTime,omitempty"`

	// IsLive Whether stream is currently live
	IsLive bool `json:"isLive"`

	// NextDj Name of next DJ
	NextDj *string `json:"nextDj,omitempty"`

	// NextStartTime Start time of next session
	NextStartTime *time.Time `json:"nextStartTime,omitempty"`
}

// TimeSlot defines model for TimeSlot.
type TimeSlot struct {
	Available bool      `json:"available"`
	EndTime   time.Time `json:"endTime"`
	StartTime time.Time `json:"startTime"`
}

// GetAvailableSlotsParams defines parameters for GetAvailableSlots.
type GetAvailableSlotsParams struct {
	StartTime time.Time  `form:"startTime" json:"startTime"`
	EndTime   *time.Time `form:"endTime,omitempty" json:"endTime,omitempty"`
}

// DeleteReservationJSONBody defines parameters for DeleteReservation.
type DeleteReservationJSONBody struct {
	// Passcode 4-digit passcode
	Passcode string `json:"passcode"`
}

// CreateReservationJSONRequestBody defines body for CreateReservation for application/json ContentType.
type CreateReservationJSONRequestBody = CreateReservationRequest

// DeleteReservationJSONRequestBody defines body for DeleteReservation for application/json ContentType.
type DeleteReservationJSONRequestBody DeleteReservationJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get available time slots within a time range
	// (GET /available-slots)
	GetAvailableSlots(ctx echo.Context, params GetAvailableSlotsParams) error
	// Get reservations for today and tomorrow
	// (GET /reservations)
	GetReservations(ctx echo.Context) error
	// Create a new reservation
	// (POST /reservations)
	CreateReservation(ctx echo.Context) error
	// Delete a reservation
	// (DELETE /reservations/{reservationId})
	DeleteReservation(ctx echo.Context, reservationId openapi_types.UUID) error
	// Get current stream status
	// (GET /stream/status)
	GetStreamStatus(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAvailableSlots converts echo context to params.
func (w *ServerInterfaceWrapper) GetAvailableSlots(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAvailableSlotsParams
	// ------------- Required query parameter "startTime" -------------

	err = runtime.BindQueryParameter("form", true, true, "startTime", ctx.QueryParams(), &params.StartTime)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter startTime: %s", err))
	}

	// ------------- Optional query parameter "endTime" -------------

	err = runtime.BindQueryParameter("form", true, false, "endTime", ctx.QueryParams(), &params.EndTime)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter endTime: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAvailableSlots(ctx, params)
	return err
}

// GetReservations converts echo context to params.
func (w *ServerInterfaceWrapper) GetReservations(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReservations(ctx)
	return err
}

// CreateReservation converts echo context to params.
func (w *ServerInterfaceWrapper) CreateReservation(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateReservation(ctx)
	return err
}

// DeleteReservation converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteReservation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "reservationId" -------------
	var reservationId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "reservationId", runtime.ParamLocationPath, ctx.Param("reservationId"), &reservationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter reservationId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteReservation(ctx, reservationId)
	return err
}

// GetStreamStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetStreamStatus(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStreamStatus(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/available-slots", wrapper.GetAvailableSlots)
	router.GET(baseURL+"/reservations", wrapper.GetReservations)
	router.POST(baseURL+"/reservations", wrapper.CreateReservation)
	router.DELETE(baseURL+"/reservations/:reservationId", wrapper.DeleteReservation)
	router.GET(baseURL+"/stream/status", wrapper.GetStreamStatus)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xXW2/iOBT+K0feeehIaYHZ7s5s3tjCVlQMVMDMPoy6lZscwJVjZ2yHFlX895XtAAkJ",
	"NHPRPLXEx+fyne9c/EIimaRSoDCahC9ER0tMqPv3SiE1OEGNakUNk2KCXzPUxp6lSqaoDEMnGT+OaILu",
	"P9SRYqmVJiHp3UDMdMrpGgRNEM4wkY9MA+VcPmH8lgQkoc9DFAuzJGGn3Q5IwsTud0DMOkUSEm0UEwuy",
	"CQiKeMbqTH3MtIEHBCmg88d5wkRmEJgw1neuA0joM3RgKTMFcyUT0IYqQwIylyqhhoQkpgbPjdVdYzal",
	"WkcyrrF7eR6zBTOwlYC5VBAjR3dubxqDykr+96V9/tfdy+XmTZ0F58/3hNYwhk1AFH7NmMKYhF+2GSva",
	"3YNbiPdup0g+PGJkrKt9paSqkmCLD4ossSZmg4/9+6vx6J/h4GpGAnLbnc7u7UcSkMHoc3c46Lmf94PR",
	"rD/53B2SgPQ+TbqzwXh0PxuP74fj0XVB9rY7nV6Ne5Xrk+7o2n50f/3F7uS6X3B9j3KCWtOFc/M0Pi6Y",
	"vXwdDIXCqAHD1U7cdcXSjGM/sYhOlU0zZ1hcks0yFr/K2u+godP6Chf3UNZlYWoU0mRqqMl0TRoypVCY",
	"3mMVVmsT5BxyEejdwJnIOAc2ByFBCgSmwbbDOOMe5kr4+d3+sabUFzFYHIp2NGrtW0OzTOT3psf7gzv6",
	"YTtMD9mqRvu/SzRLVKAd0BaT3AJfA7c3droepORIhVUm8Pkk6PYcejd1ftijxsE6Pd8W6SEDfdh11LIO",
	"TLmsmXd0RRmnD7zYSArRf3O1/WgZ1RfO3stqdFYDE3NZBbh7O3AzrHcDuHJEcolnYgE0p7OxSiGhgi4w",
	"QWHHqGHGomGbVd/dmu5uTdfaYALd2wEJyAqV9nY6F+2Ltg1epihoykhIfnef3MxcOpxbuxDONZd+QVmg",
	"S4hNh+u9g5iE5BpNdys6dZJWi6IJGlSahF9eCLNGv2ao1iQgwnXaEm57PI3KMMgXoWMElHMwSwSnDxQV",
	"C4SzwXQMH/5sd+DT7Ap8Ft82JmW9g/tkHnPHtpimzlxAD+c040aDkfD+nVuHdGEfsrZ8/zOQKrliMcYX",
	"TUO4sxjqVArti+Rdu+3XAmEsR2zZpClnkcta61H7sbmPixlM3MU3CuckJL+19ptpK19LW7ua3OwcoErR",
	"tWf0AZO3jPDtwjEInphZMuHw0ilGbM4w9phZlZff6PMpV/2aVOPXQKwoZ/lk8OmSCvA5Qow1vH937rZU",
	"zhJmXKXrLEmoWnuaAz0RFS3otBmiC8t9m5btpqLJnVXZKn06UVWTotyvSHBxq2qQ4yHTrhhL8VRBKx67",
	"7mZkTNe+oclEKiWfjuMVkFTqGngq76O8i6A2f8t4/dOIdPQdtinPAdu3NpUcdX6aH6XUVFNROIZ8Z/vl",
	"JZXDD2euDiIp5pxFJrCvM780BIAmunh7QBGPMFAQ+FTkSvMaar0Ufg3ijW/UHA1WedNz38u8qRtWdgzu",
	"R0FJ/8l59crW7hv199G0vAY1fxU3fggfLDYn3qFNuH9Z9azIUp+gnKWdquyWVTsvnOArSu3snMtMxAcc",
	"81kH2pxffvFq6d3b5liTLr2BfrBJnyq/kp2aKrzaPj3yp4LwTPT94rAlR2VhvfV+C4j/bqGwV1GttrWR",
	"KU5CsjQmDVstLiPKl1Kb8EP7Q7tFU9ZadcjmbvN/AAAA//+Df6A02BIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
