services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:18080/api/v1}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped