services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
      - mediamtx
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        # 開発環境では localhost を使用
        # 本番環境では PRODUCTION_DOMAIN 環境変数で実際のドメインを指定
        - VITE_API_BASE_URL=${PRODUCTION_DOMAIN:-http://localhost}/api/v1
        - VITE_HLS_ENDPOINT=${PRODUCTION_DOMAIN:-http://localhost}/hls/stream-endpoint/index.m3u8
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stream_system
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: stream_system
      DB_SSLMODE: disable
      LOG_LEVEL: debug
      EVENT_START_TIME: ${EVENT_START_TIME:-2025-08-29 00:00:00}
      EVENT_END_TIME: ${EVENT_END_TIME:-2025-08-31 14:59:59}
      EVENT_TIMEZONE: ${EVENT_TIMEZONE:-Asia/Tokyo}
    volumes:
      - ./media:/app/media
    depends_on:
      postgres:
        condition: service_healthy

  mediamtx:
    # image: bluenviron/mediamtx:1.14.0
    build: ./mediamtx
    ports:
      # RTMP (incoming video) port
      - "19350:1935"

volumes:
  postgres_data:
