services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
      - mediamtx
    restart: unless-stopped

  frontend:
    image: ghcr.io/outductor/stream-system-frontend:latest
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: stream_system
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/outductor/stream-system-backend:latest
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: stream_system
      DB_SSLMODE: disable
      RTMP_PORT: 1935
      RTMP_STREAM_KEY: ${RTMP_STREAM_KEY:-dsr2025}
      HLS_OUTPUT_DIR: /app/media
      LOG_LEVEL: ${LOG_LEVEL:-info}
      EVENT_END_TIME: ${EVENT_END_TIME:-2025-08-31}
      EVENT_TIMEZONE: ${EVENT_TIMEZONE:-Asia/Tokyo}
    volumes:
      - ./media:/app/media
    depends_on:
      postgres:
        condition: service_healthy

  mediamtx:
    image: ghcr.io/outductor/stream-system-mediamtx:latest
    ports:
      # RTMP (incoming video) port
      - "19350:1935"

volumes:
  postgres_data: