services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stream_system
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-api-server:
    build: .
    ports:
      - "18080:8080"
      - "11935:1935"
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: stream_system
      DB_SSLMODE: disable
      RTMP_PORT: 1935
      RTMP_STREAM_KEY: djevent2024
      HLS_OUTPUT_DIR: /app/media
      LOG_LEVEL: debug
    volumes:
      - ./media:/app/media
    depends_on:
      postgres:
        condition: service_healthy

  mediamtx:
    build: ./mediamtx
    ports:
      # RTMP (incoming video) port
      - "19350:1935"
      # HLS (outgoing video) port
      - "8888:8888"

volumes:
  postgres_data:
