// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	DURATIONTOOLONG     ErrorCode = "DURATION_TOO_LONG"
	INVALIDPASSCODE     ErrorCode = "INVALID_PASSCODE"
	INVALIDTIMEINTERVAL ErrorCode = "INVALID_TIME_INTERVAL"
	PASTTIME            ErrorCode = "PAST_TIME"
	TIMECONFLICT        ErrorCode = "TIME_CONFLICT"
)

// CreateReservationRequest defines model for CreateReservationRequest.
type CreateReservationRequest struct {
	// DjName DJ display name (emojis allowed)
	DjName string `json:"djName"`

	// EndTime Must be on 15-minute intervals, max 1 hour from start
	EndTime time.Time `json:"endTime"`

	// Passcode 4-digit passcode for deletion
	Passcode string `json:"passcode"`

	// StartTime Must be on 15-minute intervals
	StartTime time.Time `json:"startTime"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// Reservation defines model for Reservation.
type Reservation struct {
	CreatedAt time.Time `json:"createdAt"`

	// DjName DJ display name (emojis allowed)
	DjName    string             `json:"djName"`
	EndTime   time.Time          `json:"endTime"`
	Id        openapi_types.UUID `json:"id"`
	StartTime time.Time          `json:"startTime"`
}

// StreamStatus defines model for StreamStatus.
type StreamStatus struct {
	// CurrentDj Name of current DJ (null if no one is scheduled)
	CurrentDj *string `json:"currentDj,omitempty"`

	// CurrentEndTime End time of current session
	CurrentEndTime *time.Time `json:"currentEndTime,omitempty"`

	// CurrentStartTime Start time of current session
	CurrentStartTime *time.Time `json:"currentStartTime,omitempty"`

	// IsLive Whether stream is currently live
	IsLive bool `json:"isLive"`

	// NextDj Name of next DJ
	NextDj *string `json:"nextDj,omitempty"`

	// NextStartTime Start time of next session
	NextStartTime *time.Time `json:"nextStartTime,omitempty"`
}

// TimeSlot defines model for TimeSlot.
type TimeSlot struct {
	Available bool      `json:"available"`
	EndTime   time.Time `json:"endTime"`
	StartTime time.Time `json:"startTime"`
}

// GetAvailableSlotsParams defines parameters for GetAvailableSlots.
type GetAvailableSlotsParams struct {
	Date openapi_types.Date `form:"date" json:"date"`
}

// GetReservationsParams defines parameters for GetReservations.
type GetReservationsParams struct {
	// Date Filter by date (optional, defaults to today and tomorrow)
	Date *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
}

// DeleteReservationJSONBody defines parameters for DeleteReservation.
type DeleteReservationJSONBody struct {
	// Passcode 4-digit passcode
	Passcode string `json:"passcode"`
}

// CreateReservationJSONRequestBody defines body for CreateReservation for application/json ContentType.
type CreateReservationJSONRequestBody = CreateReservationRequest

// DeleteReservationJSONRequestBody defines body for DeleteReservation for application/json ContentType.
type DeleteReservationJSONRequestBody DeleteReservationJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get available time slots
	// (GET /available-slots)
	GetAvailableSlots(ctx echo.Context, params GetAvailableSlotsParams) error
	// Get reservations for today and tomorrow
	// (GET /reservations)
	GetReservations(ctx echo.Context, params GetReservationsParams) error
	// Create a new reservation
	// (POST /reservations)
	CreateReservation(ctx echo.Context) error
	// Delete a reservation
	// (DELETE /reservations/{reservationId})
	DeleteReservation(ctx echo.Context, reservationId openapi_types.UUID) error
	// Get current stream status
	// (GET /stream/status)
	GetStreamStatus(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAvailableSlots converts echo context to params.
func (w *ServerInterfaceWrapper) GetAvailableSlots(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAvailableSlotsParams
	// ------------- Required query parameter "date" -------------

	err = runtime.BindQueryParameter("form", true, true, "date", ctx.QueryParams(), &params.Date)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAvailableSlots(ctx, params)
	return err
}

// GetReservations converts echo context to params.
func (w *ServerInterfaceWrapper) GetReservations(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReservationsParams
	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameter("form", true, false, "date", ctx.QueryParams(), &params.Date)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReservations(ctx, params)
	return err
}

// CreateReservation converts echo context to params.
func (w *ServerInterfaceWrapper) CreateReservation(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateReservation(ctx)
	return err
}

// DeleteReservation converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteReservation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "reservationId" -------------
	var reservationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "reservationId", ctx.Param("reservationId"), &reservationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter reservationId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteReservation(ctx, reservationId)
	return err
}

// GetStreamStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetStreamStatus(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStreamStatus(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/available-slots", wrapper.GetAvailableSlots)
	router.GET(baseURL+"/reservations", wrapper.GetReservations)
	router.POST(baseURL+"/reservations", wrapper.CreateReservation)
	router.DELETE(baseURL+"/reservations/:reservationId", wrapper.DeleteReservation)
	router.GET(baseURL+"/stream/status", wrapper.GetStreamStatus)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXT2/buBP9KgP+ekgBpbJ/mwW6unljt3DgJkHs7R6KbMBYY5sBRarkyK0R+LsvSMq2",
	"FCmu0vSwN1sazp/33gxHj2yus1wrVGRZ8sjsfIUZ9z/PDXLCG7Ro1pyEVjf4tUBL7l1udI6GBHrL9OGS",
	"Z+h/oZ0bkTtrlrDhBaTC5pJvQPEM4QQz/SAscCn1N0zfsohl/PsE1ZJWLOn3ehHLhNr/jxhtcmQJs2SE",
	"WrJtxFClM9EW6lNhCe4RtIL+76eZUAUhCEUud2kjyPh36MNKFwYWRmdgiRtiEVtok3FiCUs54Sk53y1h",
	"c27tXKctcc9OU7EUBDsLWGgDKUr0791JIjTO8p8vvdM/bh/Ptm/aIvh8fqa0jjVsI2bwayEMpiz5smOs",
	"GvcAbqXe270jff+Ac3KpjozRpimCHT6oisyFmI0/je7Ory4/TMbnMxax68F0ducesoiNLz8PJuOh/3s3",
	"vpyNbj4PJixiw79uBrPx1eXd7OrqbnJ1+bFiez2YTs+vhqNKTgf4MrSWL33844X7LA/2bfVVFN9SpW+K",
	"dOC7oJt4fmF3HOuHbsmItGZbFCL9oRx/Ql/e6w9EdoCyjYUpGeTZlDgVtoWGwhhUNHxowupigl5AaQLD",
	"CzhRhZQgFqA0aIUgLLg5lxYywNwovzw7em7ajFQKDodqHIvWhp7vxkR5bvp84/tXr44j7ESsW7z/vUJa",
	"oQHrgXaYlBHkBqQ7sfd1r7VErpwzhd+Pgu7ew/CiLQ/3qnOx3s/LKn2qwFB2m7RcAlOpWy4yvuZC8ntZ",
	"HSSV6l/cba9to/bGOWTZrM55EGqhmwAPrsf+chpeAK69kDzxQi2Bl3Im5xQyrvgSM1TufiRBDg03rEb+",
	"1HR/arqxhBkMrscsYms0NsTpv+u967nidY6K54Il7Df/yF+GK49zvC/h1EodNo8lekIcHX72jlOWsI9I",
	"g53p1Fs6L4ZnSGgsS748MuGCfi3QbFjElJ+0HmFWhZJMgVG53DS4aKHh1h22uVY2COP/vV644xQ5XJxU",
	"8lyKuc80frDhqjj4F4SZP/jG4IIl7H/xYc2Kyx0r3utwu0+AG8M3gcUn7O1QCC0SUHNmtsgybjYBK+Bt",
	"ZhEjvnRguZp2V5tlt+54XHt0hIabql2DhHqyH4QkNHC/AQcvnGj/gssIUlzwQpIF0kA65ZugPZ1pY/Q3",
	"N4uP0Pkfo6+6J3RgcCIsudFWA7zJYPW179cmTM8TGrFc2xb+Gqt82Rxo6U+dbl6EzTFInv1k2NYnm2vH",
	"bYOj/i/Lo0ZNk4rKayi3EMfg2QtVciyDsCS3xB6rNZcihRJ+OPGNOtdqIcWcIvchEa7BCJDm794+kUhA",
	"GDgo/FbVSvcmjx8r/8bpNtwUEgmbuhn653XdtI1fN9gP7Vrz320Mt++hoY9/Tqb1i737B1znb7YnV/WR",
	"T6Yu2j9rZlZVaSCoVGm/abtT1T4Lb/gDp0oTLHSh0icaC6wD766vsErEdr+tP3eL1Lb6Vw7pY+1Xi9PS",
	"hee7ZbpcflVQYpgXT0fyvG5sd9nvAAnPHRTuKJr1rjcKI1nCVkR5EsdSz7lcaUvJ+977XsxzEa/7bHu7",
	"/TcAAP//6bwjaoMRAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
